### ISSUE TITLE
Pre-trained weights?

### ISSUE THREAD

**Issue by madhawav** [wuyuebupt/hybridClassifier#1]
Hi, 
I believe this is the implementation of [Low-shot Face Recognition with Hybrid Classifiers
](http://openaccess.thecvf.com/content_ICCV_2017_workshops/papers/w27/Wu_Low-Shot_Face_Recognition_ICCV_2017_paper.pdf) 

Are you able to share the pre-trained weights? 
Thanks in advance

**Comment by wuyuebupt** [comment]
@madhawav 

It's almost one year since the project. It takes a little time to find the model. I attached the pre-trained model with 21000 classes. See the link below. Hope this help.

https://drive.google.com/file/d/10zfunJPS0PyPaz9sJ5qnlNKPvKVZaaSv/view?usp=sharing

**Comment by madhawav** [comment]
I will look at this. Sorry for the trouble and thanks a lot!
